version: "3.5"

services:
  client:
    # This allows for hot reload
    image: node:14.4.0-alpine
    container_name: client
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["sh", "-c", "yarn install --frozen-lockfile && yarn start"] 
    environment:
      - REACT_APP_API_URL=http://server:8000
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    networks:
      - radix
    ports:
      - "3000:3000"

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j/7687
      - NEO4J_AUTH=neo4j/password

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

volumes:
  node-modules:
    name: web_node-modules

networks:
  radix:
    name: radix