version: "3.5"

services:
  client:
    # This allows for hot reload
    image: node:14.4.0-alpine
    container_name: client
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["sh", "-c", "yarn install --frozen-lockfile && yarn start"] 
    environment:
      - REACT_APP_API_URL=http://server:8000    
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    networks:
      - radix
    ports:
      - "3000:3000"

  server:
    build: ./server
    ports:
      - "8000:8000"

volumes:
  node-modules:
    name: web_node-modules

networks:
  radix:
    name: radix