apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: gathering-metis
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: client
      src: ./client
      ports:
        - name: http
          port: 5001
      publicPort: http
    
    - name: server 
      src: ./server
      ports:
       - name: http
         port: 8000
      publicPort: http
      variables:
        NEO4J_URI: "bolt://neo4j/7687"
      secrets:
        - NEO4J_AUTH

    - name: neo4j
      image: neo4j:latest
      ports:
        - name: interface
          port: 7474
        - name: bolt
          port: 7687
      variables:
        NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      secrets:
        - NEO4J_AUTH
      environmentConfig:
        - environment: prod
          variables:
            NEO4J_dbms_memory_pagecache_size: "1G"
            NEO4J_dbms.memory.heap.initial_size: "1G"
            NEO4J_dbms_memory_heap_max__size: "1G" 
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "1G"
              cpu: "1000m"

  dnsAppAlias:
    environment: prod
    component: client
