apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: gathering-metis
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: client
      src: ./client
      ports:
        - name: http
          port: 5001
      publicPort: http
    
    - name: server
      src: "."
      ports:
       - name: http
         port: 8000
      publicPort: http
  dnsAppAlias:
    environment: prod
    component: server
