name: Build and test the frontend client
on:
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

jobs:
  build-and-test:
    name: Build and test client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        working-directory: client
        run: docker build . --file Dockerfile --tag client:$(date +%s)